version: "3.6"
services:
        basededatos:
                image: memcached
                command: memcached
        aplicacion:
                build:
                        context: python/
                        dockerfile: Dockerfile
                links:
                 - basededatos

                volumes: 
                 - ./python/:/app
volumes:
        volPython:
